/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaramAdminIndexRouteImport } from './routes/karam-admin.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as KaramAdminDashboardRouteImport } from './routes/karam-admin.dashboard'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaramAdminIndexRoute = KaramAdminIndexRouteImport.update({
  id: '/karam-admin/',
  path: '/karam-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaramAdminDashboardRoute = KaramAdminDashboardRouteImport.update({
  id: '/karam-admin/dashboard',
  path: '/karam-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/karam-admin/dashboard': typeof KaramAdminDashboardRoute
  '/books/': typeof BooksIndexRoute
  '/karam-admin/': typeof KaramAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/karam-admin/dashboard': typeof KaramAdminDashboardRoute
  '/books': typeof BooksIndexRoute
  '/karam-admin': typeof KaramAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/karam-admin/dashboard': typeof KaramAdminDashboardRoute
  '/books/': typeof BooksIndexRoute
  '/karam-admin/': typeof KaramAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/books/$bookId'
    | '/karam-admin/dashboard'
    | '/books/'
    | '/karam-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/books/$bookId'
    | '/karam-admin/dashboard'
    | '/books'
    | '/karam-admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/books/$bookId'
    | '/karam-admin/dashboard'
    | '/books/'
    | '/karam-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  KaramAdminDashboardRoute: typeof KaramAdminDashboardRoute
  BooksIndexRoute: typeof BooksIndexRoute
  KaramAdminIndexRoute: typeof KaramAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karam-admin/': {
      id: '/karam-admin/'
      path: '/karam-admin'
      fullPath: '/karam-admin/'
      preLoaderRoute: typeof KaramAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karam-admin/dashboard': {
      id: '/karam-admin/dashboard'
      path: '/karam-admin/dashboard'
      fullPath: '/karam-admin/dashboard'
      preLoaderRoute: typeof KaramAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  KaramAdminDashboardRoute: KaramAdminDashboardRoute,
  BooksIndexRoute: BooksIndexRoute,
  KaramAdminIndexRoute: KaramAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
